package Model;
// Generated 2018-11-28 10:58:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Abonnement generated by hbm2java
 */
public class Abonnement  implements java.io.Serializable {


     private BigDecimal numabonnemnt;
     private Client client;
     private Forfait forfait;
     private boolean actif;
     private Date datedebut;
     private Date datefin;
     private Set locations = new HashSet(0);

    public Abonnement() {
    }

	
    public Abonnement(BigDecimal numabonnemnt, boolean actif) {
        this.numabonnemnt = numabonnemnt;
        this.actif = actif;
    }
    public Abonnement(BigDecimal numabonnemnt, Client client, Forfait forfait, boolean actif, Date datedebut, Date datefin, Set locations) {
       this.numabonnemnt = numabonnemnt;
       this.client = client;
       this.forfait = forfait;
       this.actif = actif;
       this.datedebut = datedebut;
       this.datefin = datefin;
       this.locations = locations;
    }
   
    public BigDecimal getNumabonnemnt() {
        return this.numabonnemnt;
    }
    
    public void setNumabonnemnt(BigDecimal numabonnemnt) {
        this.numabonnemnt = numabonnemnt;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Forfait getForfait() {
        return this.forfait;
    }
    
    public void setForfait(Forfait forfait) {
        this.forfait = forfait;
    }
    public boolean isActif() {
        return this.actif;
    }
    
    public void setActif(boolean actif) {
        this.actif = actif;
    }
    public Date getDatedebut() {
        return this.datedebut;
    }
    
    public void setDatedebut(Date datedebut) {
        this.datedebut = datedebut;
    }
    public Date getDatefin() {
        return this.datefin;
    }
    
    public void setDatefin(Date datefin) {
        this.datefin = datefin;
    }
    public Set getLocations() {
        return this.locations;
    }
    
    public void setLocations(Set locations) {
        this.locations = locations;
    }




}


