package Model;
// Generated 2018-11-28 10:58:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Employe generated by hbm2java
 */
public class Employe  implements java.io.Serializable {


     private BigDecimal numemploye;
     private Personne personne;
     private BigDecimal identifiant;
     private String mdp;

    public Employe() {
    }

	
    public Employe(BigDecimal numemploye, BigDecimal identifiant, String mdp) {
        this.numemploye = numemploye;
        this.identifiant = identifiant;
        this.mdp = mdp;
    }
    public Employe(BigDecimal numemploye, Personne personne, BigDecimal identifiant, String mdp) {
       this.numemploye = numemploye;
       this.personne = personne;
       this.identifiant = identifiant;
       this.mdp = mdp;
    }
   
    public BigDecimal getNumemploye() {
        return this.numemploye;
    }
    
    public void setNumemploye(BigDecimal numemploye) {
        this.numemploye = numemploye;
    }
    public Personne getPersonne() {
        return this.personne;
    }
    
    public void setPersonne(Personne personne) {
        this.personne = personne;
    }
    public BigDecimal getIdentifiant() {
        return this.identifiant;
    }
    
    public void setIdentifiant(BigDecimal identifiant) {
        this.identifiant = identifiant;
    }
    public String getMdp() {
        return this.mdp;
    }
    
    public void setMdp(String mdp) {
        this.mdp = mdp;
    }




}


