package Model;
// Generated 2018-11-28 10:58:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Forfait generated by hbm2java
 */
public class Forfait  implements java.io.Serializable {


     private BigDecimal numforfait;
     private BigDecimal nblocationmax;
     private BigDecimal dureemax;
     private BigDecimal prixforfaitparmois;
     private Set abonnements = new HashSet(0);

    public Forfait() {
    }

	
    public Forfait(BigDecimal numforfait) {
        this.numforfait = numforfait;
    }
    public Forfait(BigDecimal numforfait, BigDecimal nblocationmax, BigDecimal dureemax, BigDecimal prixforfaitparmois, Set abonnements) {
       this.numforfait = numforfait;
       this.nblocationmax = nblocationmax;
       this.dureemax = dureemax;
       this.prixforfaitparmois = prixforfaitparmois;
       this.abonnements = abonnements;
    }
   
    public BigDecimal getNumforfait() {
        return this.numforfait;
    }
    
    public void setNumforfait(BigDecimal numforfait) {
        this.numforfait = numforfait;
    }
    public BigDecimal getNblocationmax() {
        return this.nblocationmax;
    }
    
    public void setNblocationmax(BigDecimal nblocationmax) {
        this.nblocationmax = nblocationmax;
    }
    public BigDecimal getDureemax() {
        return this.dureemax;
    }
    
    public void setDureemax(BigDecimal dureemax) {
        this.dureemax = dureemax;
    }
    public BigDecimal getPrixforfaitparmois() {
        return this.prixforfaitparmois;
    }
    
    public void setPrixforfaitparmois(BigDecimal prixforfaitparmois) {
        this.prixforfaitparmois = prixforfaitparmois;
    }
    public Set getAbonnements() {
        return this.abonnements;
    }
    
    public void setAbonnements(Set abonnements) {
        this.abonnements = abonnements;
    }




}


