package Model;
// Generated 2018-11-28 10:58:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * GenrefilmId generated by hbm2java
 */
public class GenrefilmId  implements java.io.Serializable {


     private BigDecimal numgenre;
     private BigDecimal numfilm;

    public GenrefilmId() {
    }

    public GenrefilmId(BigDecimal numgenre, BigDecimal numfilm) {
       this.numgenre = numgenre;
       this.numfilm = numfilm;
    }
   
    public BigDecimal getNumgenre() {
        return this.numgenre;
    }
    
    public void setNumgenre(BigDecimal numgenre) {
        this.numgenre = numgenre;
    }
    public BigDecimal getNumfilm() {
        return this.numfilm;
    }
    
    public void setNumfilm(BigDecimal numfilm) {
        this.numfilm = numfilm;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GenrefilmId) ) return false;
		 GenrefilmId castOther = ( GenrefilmId ) other; 
         
		 return ( (this.getNumgenre()==castOther.getNumgenre()) || ( this.getNumgenre()!=null && castOther.getNumgenre()!=null && this.getNumgenre().equals(castOther.getNumgenre()) ) )
 && ( (this.getNumfilm()==castOther.getNumfilm()) || ( this.getNumfilm()!=null && castOther.getNumfilm()!=null && this.getNumfilm().equals(castOther.getNumfilm()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNumgenre() == null ? 0 : this.getNumgenre().hashCode() );
         result = 37 * result + ( getNumfilm() == null ? 0 : this.getNumfilm().hashCode() );
         return result;
   }   


}


