package Model;
// Generated 2018-11-28 10:58:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Genre generated by hbm2java
 */
public class Genre  implements java.io.Serializable {


     private BigDecimal numgenre;
     private String genre;
     private String description;
     private Set genrefilms = new HashSet(0);

    public Genre() {
    }

	
    public Genre(BigDecimal numgenre, String genre) {
        this.numgenre = numgenre;
        this.genre = genre;
    }
    public Genre(BigDecimal numgenre, String genre, String description, Set genrefilms) {
       this.numgenre = numgenre;
       this.genre = genre;
       this.description = description;
       this.genrefilms = genrefilms;
    }
   
    public BigDecimal getNumgenre() {
        return this.numgenre;
    }
    
    public void setNumgenre(BigDecimal numgenre) {
        this.numgenre = numgenre;
    }
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getGenrefilms() {
        return this.genrefilms;
    }
    
    public void setGenrefilms(Set genrefilms) {
        this.genrefilms = genrefilms;
    }




}


