package Model;
// Generated 2018-11-28 10:58:41 by Hibernate Tools 4.3.1



/**
 * Genrefilm generated by hbm2java
 */
public class Genrefilm  implements java.io.Serializable {


     private GenrefilmId id;
     private Genre genre;
     private Film film;

    public Genrefilm() {
    }

	
    public Genrefilm(GenrefilmId id) {
        this.id = id;
    }
    public Genrefilm(GenrefilmId id, Genre genre, Film film) {
       this.id = id;
       this.genre = genre;
       this.film = film;
    }
   
    public GenrefilmId getId() {
        return this.id;
    }
    
    public void setId(GenrefilmId id) {
        this.id = id;
    }
    public Genre getGenre() {
        return this.genre;
    }
    
    public void setGenre(Genre genre) {
        this.genre = genre;
    }
    public Film getFilm() {
        return this.film;
    }
    
    public void setFilm(Film film) {
        this.film = film;
    }




}


