package Model;
// Generated 2018-11-28 10:58:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private BigDecimal numlocation;
     private Abonnement abonnement;
     private Item item;
     private Date datedebut;
     private BigDecimal fraisretard;

    public Location() {
    }
	
    public Location(BigDecimal numlocation) {
        this.numlocation = numlocation;
    }
    public Location(BigDecimal numlocation, Abonnement abonnement, Item item, Date datedebut, BigDecimal fraisretard) {
       this.numlocation = numlocation;
       this.abonnement = abonnement;
       this.item = item;
       this.datedebut = datedebut;
       this.fraisretard = fraisretard;
    }
   
    public BigDecimal getNumlocation() {
        return this.numlocation;
    }
    
    public void setNumlocation(BigDecimal numlocation) {
        this.numlocation = numlocation;
    }
    public Abonnement getAbonnement() {
        return this.abonnement;
    }
    
    public void setAbonnement(Abonnement abonnement) {
        this.abonnement = abonnement;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }
    public Date getDatedebut() {
        return this.datedebut;
    }
    
    public void setDatedebut(Date datedebut) {
        this.datedebut = datedebut;
    }
    public BigDecimal getFraisretard() {
        return this.fraisretard;
    }
    
    public void setFraisretard(BigDecimal fraisretard) {
        this.fraisretard = fraisretard;
    }




}


