package Model;
// Generated 2018-11-28 10:58:41 by Hibernate Tools 4.3.1



/**
 * Participantfilm generated by hbm2java
 */
public class Participantfilm  implements java.io.Serializable {


     private ParticipantfilmId id;
     private Film film;
     private Participant participant;

    public Participantfilm() {
    }

	
    public Participantfilm(ParticipantfilmId id) {
        this.id = id;
    }
    public Participantfilm(ParticipantfilmId id, Film film, Participant participant) {
       this.id = id;
       this.film = film;
       this.participant = participant;
    }
   
    public ParticipantfilmId getId() {
        return this.id;
    }
    
    public void setId(ParticipantfilmId id) {
        this.id = id;
    }
    public Film getFilm() {
        return this.film;
    }
    
    public void setFilm(Film film) {
        this.film = film;
    }
    public Participant getParticipant() {
        return this.participant;
    }
    
    public void setParticipant(Participant participant) {
        this.participant = participant;
    }




}


