package Model;
// Generated 2018-11-28 10:58:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Participant generated by hbm2java
 */
public class Participant  implements java.io.Serializable {


     private BigDecimal numparticipant;
     private String nom;
     private String prenom;
     private Date datenaissance;
     private String lieunaissance;
     private String biographie;
     private String typeparticipant;
     private Set personnages = new HashSet(0);
     private Set participantfilms = new HashSet(0);

    public Participant() {
    }

	
    public Participant(BigDecimal numparticipant, String nom) {
        this.numparticipant = numparticipant;
        this.nom = nom;
    }
    public Participant(BigDecimal numparticipant, String nom, String prenom, Date datenaissance, String lieunaissance, String biographie, String typeparticipant, Set personnages, Set participantfilms) {
       this.numparticipant = numparticipant;
       this.nom = nom;
       this.prenom = prenom;
       this.datenaissance = datenaissance;
       this.lieunaissance = lieunaissance;
       this.biographie = biographie;
       this.typeparticipant = typeparticipant;
       this.personnages = personnages;
       this.participantfilms = participantfilms;
    }
   
    public BigDecimal getNumparticipant() {
        return this.numparticipant;
    }
    
    public void setNumparticipant(BigDecimal numparticipant) {
        this.numparticipant = numparticipant;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public Date getDatenaissance() {
        return this.datenaissance;
    }
    
    public void setDatenaissance(Date datenaissance) {
        this.datenaissance = datenaissance;
    }
    public String getLieunaissance() {
        return this.lieunaissance;
    }
    
    public void setLieunaissance(String lieunaissance) {
        this.lieunaissance = lieunaissance;
    }
    public String getBiographie() {
        return this.biographie;
    }
    
    public void setBiographie(String biographie) {
        this.biographie = biographie;
    }
    public String getTypeparticipant() {
        return this.typeparticipant;
    }
    
    public void setTypeparticipant(String typeparticipant) {
        this.typeparticipant = typeparticipant;
    }
    public Set getPersonnages() {
        return this.personnages;
    }
    
    public void setPersonnages(Set personnages) {
        this.personnages = personnages;
    }
    public Set getParticipantfilms() {
        return this.participantfilms;
    }
    
    public void setParticipantfilms(Set participantfilms) {
        this.participantfilms = participantfilms;
    }




}


