package Model;
// Generated 2018-11-28 10:58:41 by Hibernate Tools 4.3.1



/**
 * Paysproduction generated by hbm2java
 */
public class Paysproduction  implements java.io.Serializable {


     private PaysproductionId id;
     private Film film;
     private Pays pays;

    public Paysproduction() {
    }

	
    public Paysproduction(PaysproductionId id) {
        this.id = id;
    }
    public Paysproduction(PaysproductionId id, Film film, Pays pays) {
       this.id = id;
       this.film = film;
       this.pays = pays;
    }
   
    public PaysproductionId getId() {
        return this.id;
    }
    
    public void setId(PaysproductionId id) {
        this.id = id;
    }
    public Film getFilm() {
        return this.film;
    }
    
    public void setFilm(Film film) {
        this.film = film;
    }
    public Pays getPays() {
        return this.pays;
    }
    
    public void setPays(Pays pays) {
        this.pays = pays;
    }




}


