package Model;
// Generated 2018-11-28 10:58:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * PaysproductionId generated by hbm2java
 */
public class PaysproductionId  implements java.io.Serializable {


     private BigDecimal numpays;
     private BigDecimal numfilm;

    public PaysproductionId() {
    }

    public PaysproductionId(BigDecimal numpays, BigDecimal numfilm) {
       this.numpays = numpays;
       this.numfilm = numfilm;
    }
   
    public BigDecimal getNumpays() {
        return this.numpays;
    }
    
    public void setNumpays(BigDecimal numpays) {
        this.numpays = numpays;
    }
    public BigDecimal getNumfilm() {
        return this.numfilm;
    }
    
    public void setNumfilm(BigDecimal numfilm) {
        this.numfilm = numfilm;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PaysproductionId) ) return false;
		 PaysproductionId castOther = ( PaysproductionId ) other; 
         
		 return ( (this.getNumpays()==castOther.getNumpays()) || ( this.getNumpays()!=null && castOther.getNumpays()!=null && this.getNumpays().equals(castOther.getNumpays()) ) )
 && ( (this.getNumfilm()==castOther.getNumfilm()) || ( this.getNumfilm()!=null && castOther.getNumfilm()!=null && this.getNumfilm().equals(castOther.getNumfilm()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNumpays() == null ? 0 : this.getNumpays().hashCode() );
         result = 37 * result + ( getNumfilm() == null ? 0 : this.getNumfilm().hashCode() );
         return result;
   }   


}


