package Model;
// Generated 2018-11-28 10:58:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Pays generated by hbm2java
 */
public class Pays  implements java.io.Serializable {


     private BigDecimal numpays;
     private String nom;
     private Set paysproductions = new HashSet(0);

    public Pays() {
    }

	
    public Pays(BigDecimal numpays, String nom) {
        this.numpays = numpays;
        this.nom = nom;
    }
    public Pays(BigDecimal numpays, String nom, Set paysproductions) {
       this.numpays = numpays;
       this.nom = nom;
       this.paysproductions = paysproductions;
    }
   
    public BigDecimal getNumpays() {
        return this.numpays;
    }
    
    public void setNumpays(BigDecimal numpays) {
        this.numpays = numpays;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Set getPaysproductions() {
        return this.paysproductions;
    }
    
    public void setPaysproductions(Set paysproductions) {
        this.paysproductions = paysproductions;
    }




}


