package Model;
// Generated 2018-11-28 10:58:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Personnage generated by hbm2java
 */
public class Personnage  implements java.io.Serializable {


     private BigDecimal numpersonnage;
     private Film film;
     private Participant participant;
     private String nom;
     private String descriptionperso;

    public Personnage() {
    }

	
    public Personnage(BigDecimal numpersonnage, String nom) {
        this.numpersonnage = numpersonnage;
        this.nom = nom;
    }
    public Personnage(BigDecimal numpersonnage, Film film, Participant participant, String nom, String descriptionperso) {
       this.numpersonnage = numpersonnage;
       this.film = film;
       this.participant = participant;
       this.nom = nom;
       this.descriptionperso = descriptionperso;
    }
   
    public BigDecimal getNumpersonnage() {
        return this.numpersonnage;
    }
    
    public void setNumpersonnage(BigDecimal numpersonnage) {
        this.numpersonnage = numpersonnage;
    }
    public Film getFilm() {
        return this.film;
    }
    
    public void setFilm(Film film) {
        this.film = film;
    }
    public Participant getParticipant() {
        return this.participant;
    }
    
    public void setParticipant(Participant participant) {
        this.participant = participant;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getDescriptionperso() {
        return this.descriptionperso;
    }
    
    public void setDescriptionperso(String descriptionperso) {
        this.descriptionperso = descriptionperso;
    }




}


